apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  namespace: default
  labels:
    app: ml-app
spec:
  type: NodePort
  selector:
    app: ml-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30007

